# 휴스키 A200 매뉴얼 기준 로봇 크기 설정
footprint: [[-0.495, -0.335], [-0.495, 0.335], [0.495, 0.335], [0.495, -0.335]]
footprint_padding: 0.01

# 복셀 그리드 레이어 설정 (3D 장애물 감지용)
voxel_layer:
  enabled: true
  publish_voxel_map: true
  origin_z: -1.0
  z_resolution: 0.05
  z_voxels: 20
  max_obstacle_height: 2.0
  mark_threshold: 1
  unknown_threshold: 15
  combination_method: 1
  obstacle_range: 5.0
  raytrace_range: 6.0
  track_unknown_space: true
  footprint_clearing_enabled: true
  observation_sources: point_cloud_sensor

  # 벨로다인 포인트 클라우드 설정
  point_cloud_sensor:
    data_type: PointCloud2
    topic: /velodyne_points_range_limited
    sensor_frame: velodyne
    marking: true
    clearing: true
    min_obstacle_height: -0.25
    max_obstacle_height: 1.8
    obstacle_range: 5.0
    raytrace_range: 6.0
    expected_update_rate: 10.0
    observation_persistence: 0.0

# 인플레이션 레이어 설정
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0   # 더 넓은 범위에서 장애물 비용을 유지
  inflation_radius: 0.7      # 장애물 주변 인플레이션 반경 (m)