# 휴스키 A200 매뉴얼 기준 로봇 크기 설정
footprint: [[-0.495, -0.335], [-0.495, 0.335], [0.495, 0.335], [0.495, -0.335]]
footprint_padding: 0.01

# 장애물 레이어 설정
obstacle_layer:
  enabled: true
  max_obstacle_height: 2.0
  min_obstacle_height: 0.08
  obstacle_range: 4.5
  raytrace_range: 5.0
  inflation_radius: 0.55
  track_unknown_space: true
  combination_method: 1
  observation_sources: velodyne_cloud

  # 벨로다인 라이다 설정
  velodyne_cloud:
    data_type: PointCloud2
    topic: /velodyne_points_filtered
    sensor_frame: velodyne
    marking: true
    clearing: true
    expected_update_rate: 10.0
    min_obstacle_height: 0.15
    max_obstacle_height: 2.0
    obstacle_range: 4.5
    raytrace_range: 5.0

# 3D 복셀 레이어 설정
voxel_layer:
  enabled: true
  publish_voxel_map: true
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 16
  max_obstacle_height: 2.0
  unknown_threshold: 9
  mark_threshold: 0
  combination_method: 1
  obstacle_range: 4.5
  raytrace_range: 5.0
  observation_sources: velodyne_cloud
  
  velodyne_cloud:
    data_type: PointCloud2
    topic: /velodyne_points_filtered
    sensor_frame: velodyne
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.15

# 인플레이션 레이어 설정
inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.6