# Husky A200 매뉴얼 기준 로봇 크기 설정
footprint: [[-0.495, -0.335], [-0.495, 0.335], [0.495, 0.335], [0.495, -0.335]]
footprint_padding: 0.01

# Voxel 그리드 레이어 설정 (3D 장애물 감지용)
voxel_layer:
  enabled: true
  publish_voxel_map: true  # 디버깅을 위해 voxel map 게시
  origin_z: -1.0           # z축 원점 (지면 아래 포함)
  z_resolution: 0.1        # z축 해상도
  z_voxels: 20             # z축 voxel 수
  max_obstacle_height: 2.0  # 최대 장애물 높이
  unknown_threshold: 15    # 알 수 없는 상태로 표시하기 위한 임계값
  mark_threshold: 0        # 장애물로 표시하기 위한 임계값
  combination_method: 1    # 1: 최대값, 0: 평균값
  track_unknown_space: true  # 알 수 없는 공간 추적
  obstacle_range: 8.0      # 장애물 감지 범위
  raytrace_range: 10.0     # 클리어링 범위
  footprint_clearing_enabled: true  # 로봇 내부 영역 항상 클리어
  observation_sources: point_cloud_sensor

  # 벨로다인 포인트 클라우드 설정
  point_cloud_sensor:
    data_type: PointCloud2
    topic: /velodyne_points_final  # 필터링된 최종 포인트 클라우드
    sensor_frame: velodyne
    marking: true
    clearing: true
    min_obstacle_height: 0.15     
    max_obstacle_height: 1.8      # 로봇 위의 장애물 감지
    observation_persistence: 0.0  # 관측이 지속되는 시간 (0: 즉시 업데이트)
    expected_update_rate: 10.0    # 예상 업데이트 빈도
    
# 인플레이션 레이어 설정
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0   # 비용 감소 비율
  inflation_radius: 2.0      # 장애물 주변 인플레이션 반경 (m)