# =============================================================================
# 25_Jairlab 기반 DWA 파라미터 설정 (Gazebo 시뮬레이션용)
# 25_Jairlab의 robot_dynamics_params.yaml과 path_planning_params.yaml 통합
# =============================================================================

DWAPlannerROS:
  # ==========================================================================
  # 로봇 동역학 설정 (25_Jairlab robot_dynamics_params.yaml 기반)
  # ==========================================================================
  max_vel_x: 1.0        # 최대 전진 속도 (m/s) - 로봇이 낼 수 있는 최고 속도
  min_vel_x: -1.0       # 최소 전진 속도 (m/s) - 후진 시 최대 속도 (음수)
  max_vel_y: 0.0        # 최대 Y축 속도 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  min_vel_y: 0.0        # 최소 Y축 속도 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  max_vel_trans: 1.0    # 최대 이동 속도 (m/s) - 실제 사용할 최대 속도 제한
  min_vel_trans: 0.1    # 최소 이동 속도 (m/s) - 너무 느린 움직임 방지
  max_vel_theta: 0.8    # 최대 회전 속도 (rad/s) - 제자리 회전 시 최대 각속도
  min_vel_theta: 0.08   # 최소 회전 속도 (rad/s) - 너무 느린 회전 방지

  # 가속도 제한 설정 (디퍼렌셜 드라이브 진동 최소화)
  acc_lim_x: 2.5        # X축 가속도 제한 (m/s^2) - 부드러운 전진/후진
  acc_lim_y: 0.0        # Y축 가속도 제한 (m/s^2) - 비홀로노믹 로봇이므로 0
  acc_lim_theta: 2.5    # 회전 가속도 제한 (rad/s^2) - 진동 감소를 위한 적절한 가속도

  # ==========================================================================
  # 목표 도달 허용치 (언제 목표에 도달했다고 판단할지)
  # ==========================================================================
  xy_goal_tolerance: 0.5        # 위치 허용 오차 (m) - 더 정밀한 도달 요구로 큰 회전 반경 허용
  yaw_goal_tolerance: 3.14      # 방향 허용 오차 (rad) - 전체 원주각 허용으로 방향 제약 제거
  latch_xy_goal_tolerance: false # 위치 도달 후 이동 허용 - 큰 회전 반경으로 목표 접근 가능
  penalize_negative_x: false    # 후진 패널티 비활성화 - 전진/후진 모두 허용으로 유연성 증대

  # ==========================================================================
  # 안전 설정 (충돌 방지 및 안전한 정지)
  # ==========================================================================
  stop_time_buffer: 0.2         # 정지 시간 버퍼 (s) - 장애물 감지 시 안전하게 정지하기 위한 여유 시간
  scaling_speed: 0.1            # 속도 스케일링 임계값 (m/s) - 낮은 속도에서만 반경 축소
  max_scaling_factor: 0.5       # 최대 스케일링 팩터 - 더 큰 회전 반경 허용

  # ==========================================================================
  # 경로 평가 가중치 설정 (부드러운 움직임을 위한 가중치 조정)
  # 디퍼렌셜 드라이브 진동 최소화를 위한 최적화
  # ==========================================================================
  path_distance_bias: 32.0      # 글로벌 경로 따르기 가중치 - 추가 감소로 큰 회전 반경 허용
  goal_distance_bias: 32.0      # 목표점 도달 가중치 - 균형 잡힌 가중치로 유연성 증대
  occdist_scale: 0.02           # 장애물 회피 가중치 - 약간 증가로 안전성 유지
  forward_point_distance: 0.5   # 로봇 앞쪽 참조점 거리 (m) - 더 먼 미래 예측으로 경로 계획 개선

  # ==========================================================================
  # 궤적 시뮬레이션 설정 (DWA 알고리즘의 핵심 파라미터)
  # ==========================================================================
  sim_time: 4.0           # 경로 시뮬레이션 시간 (s) - 더 긴 예측으로 큰 회전 반경 계획
  sim_granularity: 0.05   # 시뮬레이션 단계 크기 (m) - 계산 비용 절약으로 예측 거리 증대
  vx_samples: 10          # x 속도 샘플 수 - 간소화로 큰 회전 중심
  vy_samples: 0           # y 속도 샘플 수 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  vth_samples: 20         # 회전 속도 샘플 수 - 적절한 수준으로 큰 회전 가능
  controller_frequency: 10.0  # 컨트롤러 주기 (Hz) - 1초에 몇 번 궤적을 계산할지

  # ==========================================================================
  # 진동 방지 (같은 지점에서 계속 맴도는 현상 방지)
  # ==========================================================================
  oscillation_reset_dist: 0.1  # 진동 감지 거리 (m) - 이 거리 내에서 왔다갔다 하면 진동으로 판단하여 리셋

  # ==========================================================================
  # 시각화 설정 (디버깅 및 모니터링용)
  # ==========================================================================
  publish_traj_pc: true        # 궤적 포인트 클라우드 발행 - RViz에서 후보 궤적들 확인 가능
  publish_cost_grid_pc: true   # 비용 그리드 발행 - 각 궤적의 비용 시각화
  global_frame_id: odom        # 전역 프레임 ID - 좌표계 설정

# =============================================================================
# Move Base 일반 설정 (25_Jairlab path_planning_params.yaml 기반)
# 네비게이션 시스템 전반적인 동작 제어
# =============================================================================

# 제어 주기 설정 (시스템 반응 속도)
controller_frequency: 10.0  # 로컬 플래너 실행 주기 (Hz) - 장애물 회피 반응 속도
planner_frequency: 5.0       # 글로벌 플래너 실행 주기 (Hz) - 전체 경로 재계산 빈도
controller_patience: 15.0    # 로컬 플래너 대기 시간 (s) - 이 시간 내에 유효한 명령이 없으면 복구 시작
planner_patience: 5.0        # 글로벌 플래너 대기 시간 (s) - 경로 계획 실패 시 복구까지 대기 시간

# 진동 감지 및 복구 설정 (큰 회전 반경 허용)
oscillation_timeout: 30.0     # 진동 감지 시간 (초) - 더 긴 시간으로 큰 회전 허용
oscillation_distance: 2.0     # 진동 감지 거리 (m) - 더 넓은 범위로 큰 회전 허용
recovery_behavior_enabled: false   # 복구 동작 비활성화 - 제자리 회전 방지
clearing_rotation_allowed: false   # 코스트맵 클리어링 시 회전 비허용 - 제자리 회전 완전 방지
conservative_clear_costmap: false  # 비보수적 코스트맵 클리어링 - 더 유연한 경로 허용

# 플래너 설정 (사용할 알고리즘 지정)
base_local_planner: dwa_local_planner/DWAPlannerROS  # 로컬 플래너 - 장애물 회피 및 즉각적인 경로 수정
base_global_planner: global_planner/GlobalPlanner   # 글로벌 플래너 - 전체 경로 계획

# =============================================================================
# Global Planner 설정 (전체 경로 계획 알고리즘 세부 설정)
# 25_Jairlab 설정과 동일하게 구성
# =============================================================================

GlobalPlanner:
  # ==========================================================================
  # 경로 계획 알고리즘 설정
  # ==========================================================================
  allow_unknown: true           # 미지의 영역 통과 허용 - 맵에 없는 구역도 지나갈 수 있음
  use_dijkstra: true            # 다익스트라 알고리즘 사용 - 최단 경로 보장
  use_quadratic: true           # 2차 근사 사용 - 더 부드러운 경로 생성
  use_grid_path: false          # 그리드 경로 사용 안함 - 대각선 이동 허용
  old_navfn_behavior: false     # 구형 navfn 동작 사용 안함 - 개선된 알고리즘 사용

  # ==========================================================================
  # 플래너 윈도우 설정 (경로 계획 영역 제한)
  # ==========================================================================
  planner_window_x: 0.0         # 플래너 윈도우 X축 크기 (0=전체 맵 사용)
  planner_window_y: 0.0         # 플래너 윈도우 Y축 크기 (0=전체 맵 사용)
  default_tolerance: 0.0        # 기본 허용 오차 (더 정확한 경로 계획)

  # ==========================================================================
  # 발행 및 디버깅 설정
  # ==========================================================================
  publish_scale: 100            # 발행 스케일 (경로 세밀도 향상)
  planner_costmap_publish_frequency: 0.0  # 비용맵 발행 주기
  publish_potential: false      # 포텐셜 필드 발행 비활성화 (성능 향상)

  # ==========================================================================
  # 비용 함수 설정 
  # ==========================================================================
  cost_factor: 10.0              # 기본값: 3 장애물 비용 가중치 - 적절한 장애물 회피
  neutral_cost: 20              # 기본값: 50 자유 공간 기본 비용
  lethal_cost: 253              # 기본값: 253 치명적 장애물 비용