DWAPlannerROS:
  # 휴스키 A200 사양에 맞는 로봇 설정
  max_vel_x: 0.9
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.9
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.2
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  
  # 목표 허용치 매개변수
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false
  
  # 경로 시뮬레이션 매개변수
  sim_time: 2.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20
  controller_frequency: 10.0
  
  # 경로 평가 매개변수
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.04
  forward_point_distance: 0.3
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  
  # 진동 방지 매개변수
  oscillation_reset_dist: 0.05
  
  # 시각화 설정
  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: odom