# UTM 기반 글로벌 Costmap 파라미터
global_costmap:
  global_frame: utm                 # UTM 좌표계 사용
  robot_base_frame: base_link
  update_frequency: 2               # 업데이트 주기 (Hz) - 글로벌은 더 낮게
  publish_frequency: 2              # 발행 주기 (Hz)
  static_map: false                 # 정적 맵 사용 안함
  rolling_window: true              # 롤링 윈도우 모드
  width: 25.0                       # 글로벌 맵 폭 (m) - 더 넓게
  height: 25.0                      # 글로벌 맵 높이 (m)
  resolution: 0.1                   # 해상도 (m/cell) - 로컬보다 낮은 해상도
  transform_tolerance: 0.5          # TF 변환 허용 오차 (s)
  reset_distance: 0.5               # 맵 리셋 거리 (m)
  track_unknown_space: true         # 미지 공간 추적

  plugins:
    - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}