global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5
  publish_frequency: 5
  static_map: false
  rolling_window: true
  width: 100.0
  height: 100.0
  resolution: 0.1
  transform_tolerance: 0.5
  track_unknown_space: true
# global_costmap:
#   global_frame: odom
#   rolling_window: true
#   track_unknown_space: true

  plugins:
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}