global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1
  publish_frequency: 1
  static_map: false
  rolling_window: true
  width: 15.5
  height: 15.5
  resolution: 0.1
  transform_tolerance: 0.5
  reset_distance: 0.5
  track_unknown_space: true

  plugins:
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}