local_costmap:
  global_frame: map             # odom 프레임 (faster-lio 고주파수)
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  static_map: false
  rolling_window: true
  width: 35.0
  height: 35.0
  resolution: 0.05
  transform_tolerance: 0.5       # TF 대기 시간
  reset_distance: 2.5
  track_unknown_space: false

  plugins:
    - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}