shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0     # 진동 감지 시간 (초)
oscillation_distance: 0.1    # 진동 감지 거리 (m)
oscillation_reset_dist: 0.5  # 진동 리셋 거리 (m)
recovery_behavior_enabled: true
clearing_rotation_allowed: true

# 맵 외부에서 CarrotPlanner 사용 설정
use_carrot_planner_outside_map: true  # costmap 외부에서 CarrotPlanner 활성화


# 복구 동작 설정
recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

# 복구 동작 파라미터
clear_costmap_recovery:
  reset_distance: 1.0
  layer_names: ["voxel_layer"]


# CarrotPlanner 파라미터
CarrotPlanner:
  step_size: 0.2
  min_dist_from_robot: 0.1
  carrot_distance: 0.5  # 로봇 앞에 당근 마커를 배치할 거리