shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
recovery_behavior_enabled: true
clearing_rotation_allowed: true

# 복구 동작 설정
recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery


# 3D 장애물 환경에 최적화된 복구 동작 
conservative_reset:
  reset_distance: 3.0
  
aggressive_reset:
  reset_distance: 0.0